datajoint.org text updates
datajoint/datajoint.org pull request #7
Opened 2021-07-14 16:21 UTC by dimitri-yatsenko

improved wording

2021-07-14 18:06 UTC, guzman-raphael requested changes
Also, this PR now depends on the following being merged first so that the links will work.
- datajoint/datajoint-elements#25
- datajoint/datajoint-docs#266

2021-07-14 18:27 UTC, dimitri-yatsenko commented on index.html
> +            <a class="external-link" href="https://tutorials.datajoint.org" target="_blank">
i am with the link being dead if only for a couple of hours.

2021-07-14 18:28 UTC, dimitri-yatsenko commented on index.html
> +        <h2 class="sub-heading">Resources and Services</h2>
With the project being open, there is not such thing as external since there is no internal.

2021-07-14 18:31 UTC, dimitri-yatsenko commented on index.html
> +            <p class="default-text"><a class="highlight" href="https://playground.datajoint.io/" target="_blank">DataJoint Playground</a> is an online <a class="external-link" href="https://jupyter.o
This is a bit too complicated. The company develops and promotes the open source project, so there is no need to call the company "external". It's one ecosystem. The company maintains both datajoint.org, Elements, and resources.

2021-07-14 18:32 UTC, dimitri-yatsenko commented on index.html
> +            <p class="default-text grid-title"><b>More about DataJoint</b></p>
It's all run by the company and the community is still welcome to contribute.

2021-07-16 20:40 UTC, guzman-raphael approved these changes

2021-07-16 20:40 UTC, merged